---
version: '3.9'

services:
  redis:
    image: redis:alpine3.16
    container_name: redis-wsbe
    env_file: .env
    command: >
      --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}
    ports:
      - "6379:6379"
    restart: unless-stopped